version: '3.7'
services:
  mysql-server:
    image: 'mysql:8.0.19'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:5.0.1'
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'
volumes:
  mysql-data: null
